import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  knowledgeSidebar: [
    {
      type: 'category',
      label: 'VUE',
      items: [
        { type: 'autogenerated', dirName: 'vue' },
        { type: 'link', label: 'vue2官方文档', href: 'https://v2.cn.vuejs.org' },
        { type: 'link', label: 'vue3官方文档', href: 'https://cn.vuejs.org' },
      ],
    },
    {
      type: 'category',
      label: 'React',
      items: [
        { type: 'autogenerated', dirName: 'react' },
        { type: 'link', label: 'React官方文档', href: 'https://zh-hans.react.dev' },
      ],
    },
    {
      type: 'category',
      label: 'Angular',
      items: [
        { type: 'autogenerated', dirName: 'angular' },
        { type: 'link', label: 'Angular官方文档', href: 'https://angular.cn' },
      ],
    },
    'docker'
  ],
  formsSidebar: [{ type: 'autogenerated', dirName: 'forms' }],
}

export default sidebars
